cloudcloset/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('mycloset/', views.closet_index, name='index'),
    path('style/', views.style_index, name='style_index'),
    path('mycloset/tops/<int:top_id>/', views.tops_detail, name='t_detail'),
    path('mycloset/bottoms/<int:bottom_id>/', views.bottoms_detail, name='b_detail'),
    path('mycloset/coats/<int:coat_id>/', views.coats_detail, name='c_detail'),
    path('mycloset/shoes/<int:shoe_id>/', views.shoes_detail, name='s_detail'),
    path('mycloset/accessories/<int:accessory_id>/', views.accessories_detail, name='a_detail'),
    path('mycloset/tops/<int:top_id>/add_top_photo/', views.add_top_photo, name='add_top_photo'),
    path('mycloset/bottoms/<int:bottom_id>/add_bottom_photo/', views.add_bottom_photo, name='add_bottom_photo'),
    path('mycloset/coats/<int:coat_id>/add_coat_photo/', views.add_coat_photo, name='add_coat_photo'),
    path('mycloset/shoes/<int:shoe_id>/add_shoe_photo/', views.add_shoe_photo, name='add_shoe_photo'),
    path('mycloset/accessories/<int:accessory_id>/add_accessory_photo/', views.add_accessory_photo, name='add_accessory_photo'),
    path('mycloset/tops/<int:pk>/delete/', views.TopDelete.as_view(), name='tops_delete'),
    path('mycloset/bottoms/<int:pk>/delete/', views.BottomDelete.as_view(), name='bottoms_delete'),
    path('mycloset/coats/<int:pk>/delete/', views.CoatDelete.as_view(), name='coats_delete'),
    path('mycloset/shoes/<int:pk>/delete/', views.ShoeDelete.as_view(), name='shoes_delete'),
    path('mycloset/accessories/<int:pk>/delete/', views.AccessoryDelete.as_view(), name='accessories_delete'),
    path('style/create/', views.StyleCreate.as_view(), name='styles_create'),
    path('style/<int:style_id>/', views.style_detail, name='style_detail'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
# class Toptype(models.Model):
#     name = models.CharField(max_length=50)

#     def __str__(self):
#         return self.name

#     def get_absolute_url(self):
#         return reverse('toptype_detail', kwargs={'pk': self.id})


class Top(models.Model):
    category = models.CharField(max_length=100)
    # toptypes = models.ManyToManyField(Toptype)

    def __str__(self):
        return self.category

    def get_absolute_url(self):
        return reverse("t_detail", kwargs={'top_id': self.id})


class Bottom(models.Model):
    category = models.CharField(max_length=100)

    def __str__(self):
        return self.category

    def get_absolute_url(self):
        return reverse("b_detail", kwargs={'bottom_id': self.id})


class Coat(models.Model):
    category = models.CharField(max_length=100)

    def __str__(self):
        return self.category

    def get_absolute_url(self):
        return reverse("c_detail", kwargs={'coat_id': self.id})


class Shoe(models.Model):
    category = models.CharField(max_length=100)

    def __str__(self):
        return self.category

    def get_absolute_url(self):
        return reverse("s_detail", kwargs={'shoe_id': self.id})


class Accessory(models.Model):
    category = models.CharField(max_length=100)

    def __str__(self):
        return self.category

    def get_absolute_url(self):
        return reverse("a_detail", kwargs={'accessory_id': self.id})


class Topphoto(models.Model):
    url = models.CharField(max_length=200)
    top = models.ForeignKey(Top, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for top_id: {self.top_id} @{self.url}"



class Bottomphoto(models.Model):
    url = models.CharField(max_length=200)
    bottom = models.ForeignKey(Bottom, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for bottom_id: {self.bottom_id} @{self.url}"

class Coatphoto(models.Model):
    url = models.CharField(max_length=200)
    coat = models.ForeignKey(Coat, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for coat_id: {self.coat_id} @{self.url}"

class Shoephoto(models.Model):
    url = models.CharField(max_length=200)
    shoe = models.ForeignKey(Shoe, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for shoe_id: {self.shoe_id} @{self.url}"

class Accessoryphoto(models.Model):
    url = models.CharField(max_length=200)
    accessory = models.ForeignKey(Accessory, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for accessory_id: {self.accessory_id} @{self.url}"







class Outfit(models.Model):
    name = models.CharField(max_length=50)
    # topphoto = models.ManyToManyField(Topphoto)

    def __str__(self):
        return f'{self.name}'
    
    def get_absolute_url(self):
        return reverse('style_detail', kwargs={'pk': self.id})


class Style(models.Model):
    occasion = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    outfits = models.ManyToManyField(Outfit)
    # topphoto = models.ManyToManyField(Topphoto)

    def __str__(self):
        return self.occasion

    def get_absolute_url(self):
        return reverse("style_detail", kwargs={'style_id': self.id})

main_app/views.py
from django.shortcuts import render, redirect
import uuid
import boto3
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Top, Bottom, Coat, Shoe, Accessory, Topphoto, Bottomphoto, Coatphoto, Shoephoto, Accessoryphoto, Outfit, Style


S3_BASE_URL = 'https://s3.amazonaws.com/'
BUCKET = 'cloudcloset2023'


# Create your views here.
def home(request):
  return render(request, 'home.html')



def closet_index(request):
    tops = Top.objects.all()
    bottoms = Bottom.objects.all()
    coats = Coat.objects.all()
    shoes = Shoe.objects.all()
    accessories = Accessory.objects.all()
    return render(request, 'closets/index.html', { 
         'tops': tops,
         'bottoms': bottoms,
         'coats': coats,
         'shoes': shoes,
         'accessories': accessories 
    })

def style_index(request):
    styles = Style.objects.all()
    return render(request, 'style/style_index.html', { 'styles': styles })

def style_detail(request, style_id):
    style = Style.objects.get(id=style_id)
    outfits = Outfit.objects.all()
    return render(request, 'style/style_detail.html', { 'style': style, 'outfits': outfits })

def assoc_outfit(request, style_id, outfit_id):
  Style.objects.get(id=style_id).outfits.add(outfit_id)
  return redirect('style_detail', style_id=style_id)


def tops_detail(request, top_id):
    top = Top.objects.get(id=top_id)
    return render(request, 'closets/tops.html', { 'top': top})

def bottoms_detail(request, bottom_id):
    bottom = Bottom.objects.get(id=bottom_id)
    return render(request, 'closets/bottoms.html', { 'bottom': bottom })

def coats_detail(request, coat_id):
    coat = Coat.objects.get(id=coat_id)
    return render(request, 'closets/coats.html', { 'coat': coat })

def shoes_detail(request, shoe_id):
    shoe = Shoe.objects.get(id=shoe_id)
    return render(request, 'closets/shoes.html', { 'shoe': shoe })

def accessories_detail(request, accessory_id):
    accessory = Accessory.objects.get(id=accessory_id)
    #no_accessories = Accessorytype.objects.exclude(id__in=accessory.accessorytypes.all().values_list('id'))
    return render(request, 'closets/accessories.html', { 
        'accessory': accessory,
       # 'accessorytypes': no_accessories 
    })


def add_top_photo(request, top_id):
    top_photo_file = request.FILES.get('top-photo-file', None)
    if top_photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + top_photo_file.name[top_photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(top_photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            topphoto = Topphoto(url=url, top_id=top_id)
            topphoto.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('t_detail', top_id=top_id)


def add_bottom_photo(request, bottom_id):
    bottom_photo_file = request.FILES.get('bottom-photo-file', None)
    if bottom_photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + bottom_photo_file.name[bottom_photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(bottom_photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            bottomphoto = Bottomphoto(url=url, bottom_id=bottom_id)
            bottomphoto.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('b_detail', bottom_id=bottom_id)


def add_coat_photo(request, coat_id):
    coat_photo_file = request.FILES.get('coat-photo-file', None)
    if coat_photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + coat_photo_file.name[coat_photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(coat_photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            coatphoto = Coatphoto(url=url, coat_id=coat_id)
            coatphoto.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('c_detail', coat_id=coat_id)


def add_shoe_photo(request, shoe_id):
    shoe_photo_file = request.FILES.get('shoe-photo-file', None)
    if shoe_photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + shoe_photo_file.name[shoe_photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(shoe_photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            shoephoto = Shoephoto(url=url, shoe_id=shoe_id)
            shoephoto.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('s_detail', shoe_id=shoe_id)


def add_accessory_photo(request, accessory_id):
    accessory_photo_file = request.FILES.get('accessory-photo-file', None)
    if accessory_photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + accessory_photo_file.name[accessory_photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(accessory_photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            accessoryphoto = Accessoryphoto(url=url, accessory_id=accessory_id)
            accessoryphoto.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('a_detail', accessory_id=accessory_id)



#CBVs

class TopDelete(DeleteView):
  model = Topphoto
  success_url = '/mycloset/'

class BottomDelete(DeleteView):
  model = Bottomphoto
  success_url = '/mycloset/'

class CoatDelete(DeleteView):
  model = Coatphoto
  success_url = '/mycloset/'

class ShoeDelete(DeleteView):
  model = Shoephoto
  success_url = '/mycloset/'

class AccessoryDelete(DeleteView):
  model = Accessoryphoto
  success_url = '/mycloset/'


class StyleCreate(CreateView):
  model = Style
  fields = ('occasion', 'description')
  success_url = '/style/'

main_app/templates/closets/accessories.html
{% extends 'base.html' %} {% block content %}

<h1>My {{ accessory.category }}</h1>

<form
  action="{% url 'add_accessory_photo' accessory.id %}"
  enctype="multipart/form-data"
  method="POST"
  class="card-panel"
>
  {% csrf_token %}
  <input type="file" name="accessory-photo-file" />
  <br /><br />
  <input type="submit" class="btn" value="Upload Photo" />
</form>


{% for accessoryphoto in accessory.accessoryphoto_set.all %}
<div class="col s12 m7 l4">
  <div class="card small">
    <div class="card-image">
      <img class="responsive-img" src="{{accessoryphoto.url}}">
    </div>
    <div class="card-stacked">
      <div class="card-action">
        <a href="{% url 'accessories_delete' accessoryphoto.id %}">Delete</a>
      </div>
    </div>
  </div>
  {% empty %}
  <div class="card-panel teal-text center-align">You do not have any {{ accessory.category }} yet 😞</div>
{% endfor %} 

          
{% endblock %}

main_app/templates/closets/bottoms.html
{% extends 'base.html' %} {% block content %}

<h1>My {{ bottom.category }}</h1>

<form
  action="{% url 'add_bottom_photo' bottom.id %}"
  enctype="multipart/form-data"
  method="POST"
  class="card-panel"
>
  {% csrf_token %}
  <input type="file" name="bottom-photo-file" />
  <br /><br />
  <input type="submit" class="btn" value="Upload Photo" />
</form>


{% for bottomphoto in bottom.bottomphoto_set.all %}
<div class="col s12 m7 l4">
  <div class="card small">
    <div class="card-image">
      <img class="responsive-img" src="{{bottomphoto.url}}">
    </div>
    <div class="card-stacked">
      <div class="card-action">
        <a href="{% url 'bottoms_delete' bottomphoto.id %}">Delete</a>
      </div>
    </div>
  </div>
  {% empty %}
  <div class="card-panel teal-text center-align">You do not have any {{ bottom.category }} yet 😞</div>
{% endfor %} 

          
{% endblock %}

main_app/templates/closets/coats.html
{% extends 'base.html' %} {% block content %}

<h1>My {{ coat.category }}</h1>

<form
  action="{% url 'add_coat_photo' coat.id %}"
  enctype="multipart/form-data"
  method="POST"
  class="card-panel"
>
  {% csrf_token %}
  <input type="file" name="coat-photo-file" />
  <br /><br />
  <input type="submit" class="btn" value="Upload Photo" />
</form>

{% for coatphoto in coat.coatphoto_set.all %}
<div class="col s12 m7 l4">
  <div class="card small">
    <div class="card-image">
      <img class="responsive-img" src="{{coatphoto.url}}">
    </div>
    <div class="card-stacked">
      <div class="card-action">
        <a href="{% url 'coats_delete' coatphoto.id %}">Delete</a>
      </div>
    </div>
  </div>
  {% empty %}
  <div class="card-panel teal-text center-align">You do not have any {{ coat.category }} yet 😞</div>
{% endfor %} 

          
{% endblock %}

main_app/templates/closets/index.html
{% extends 'base.html' %} {% block content %}

<h1>My Closet</h1>


<div class="card">
  <div class="card-content">
    <span class="card-title">TOPS</span>
    {% for top in tops %}
      <a href="/mycloset/tops/{{ top.id }}"><p>{{top.category}}</p></a>
    {% endfor %}
  </div>
</div>



<div class="card">
  <div class="card-content">
    <span class="card-title">BOTTOMS</span>
    {% for bottom in bottoms %}
      <a href="/mycloset/bottoms/{{ bottom.id }}"><p>{{bottom.category}}</p></a>
    {% endfor %} 
  </div>
</div>



<div class="card">
  <div class="card-content">
    <span class="card-title">COATS</span>
    {% for coat in coats %}
      <a href="/mycloset/coats/{{ coat.id }}">{{coat.category}}</p></a>
    {% endfor %} 
  </div>
</div>



<div class="card">
  <div class="card-content">
    <span class="card-title">SHOES</span>
    {% for shoe in shoes %}
      <a href="/mycloset/shoes/{{ shoe.id }}"><p>{{shoe.category}}</p></a>
    {% endfor %} 
  </div>
</div>



<div class="card">
  <div class="card-content">
    <span class="card-title">ACCESSORIES</span>
    {% for accessory in accessories %}
      <a href="/mycloset/accessories/{{ accessory.id }}"><p>{{accessory.category}}</p></a>
    {% endfor %} 
  </div>
</div>

{% endblock %}

main_app/templates/closets/shoes.html
{% extends 'base.html' %} {% block content %}

<h1>My {{ shoe.category }}</h1>

<form
  action="{% url 'add_shoe_photo' shoe.id %}"
  enctype="multipart/form-data"
  method="POST"
  class="card-panel"
>
  {% csrf_token %}
  <input type="file" name="shoe-photo-file" />
  <br /><br />
  <input type="submit" class="btn" value="Upload Photo" />
</form>


{% for shoephoto in shoe.shoephoto_set.all %}
<div class="col s12 m7 l4">
  <div class="card small">
    <div class="card-image">
      <img class="responsive-img" src="{{shoephoto.url}}">
    </div>
    <div class="card-stacked">
      <div class="card-action">
        <a href="{% url 'shoes_delete' shoephoto.id %}">Delete</a>
      </div>
    </div>
  </div>
  {% empty %}
  <div class="card-panel teal-text center-align">You do not have any {{ shoe.category }} yet 😞</div>
{% endfor %} 

          
{% endblock %}

main_app/templates/closets/tops.html
{% extends 'base.html' %} {% block content %}

<h1>My {{ top.category }} Tops</h1>

<!-- {% for toptype in top.toptypes.all %}
<div class="card">
  <div class="card-content">
    <span class="card-title">
       {{ toptype.name }}
    </span>
  </div>
</div>
{% endfor %} -->


<form
  action="{% url 'add_top_photo' top.id %}"
  enctype="multipart/form-data"
  method="POST"
  class="card-panel"
>
  {% csrf_token %}
  <input type="file" name="top-photo-file" />
  <br /><br />
  <input type="submit" class="btn" value="Upload Photo" />
</form>

    

{% for topphoto in top.topphoto_set.all %}
<div class="col s12 m7 l4">
  <div class="card small">
    <div class="card-image">
      <img class="responsive-img" src="{{topphoto.url}}">
    </div>
    <div class="card-stacked">
      <div class="card-action">
        <a href="{% url 'tops_delete' topphoto.id %}">Delete</a>
      </div>
    </div>
  </div>
  {% empty %}
  <div class="card-panel teal-text center-align">You do not have any {{ top.category }} tops yet 😞</div>
{% endfor %} 

            

          
{% endblock %}